# Generated by Django 4.0.4 on 2023-03-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('road_address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=5)),
                ('tags', models.ManyToManyField(related_name='businesses', to='tag.tag')),
            ],
        ),
    ]
